# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    avoid_classes_with_only_static_members: false
    public_member_api_docs: false
    omit_local_variable_types: false
    lines_longer_than_80_chars: false
    discarded_futures: false
    cascade_invocations: false
    avoid_catches_without_on_clauses: false
    avoid_positional_boolean_parameters: false
    prefer_constructors_over_static_methods: false
    use_setters_to_change_properties: false
    no_default_cases: false
    document_ignores: false

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
